COMMAND_SIZE = 9
INT_SIZE = 8
UP       = "w        "
OBJ_OP   ="obj_obj   "
LEFT     = "a        "
DOWN     = "s        "
RIGHT    = "d        "
INTERACT = "e        "
END_OP   = "stop     "
PORT = 35041
SERVER_ADDRESS = "localhost"
